In [1]:
import pandas as pd
from datetime import date, datetime, timedelta
import numpy as np

In [ ]:
item_id = pd.read_excel(
    "./../../upgrade_mandi/raw-sheets-dump/blinkit/UPGRADE UPC.xlsx",
    sheet_name="Sheet1",
)[["Item ID", "UPC"]]

raw_file = pd.read_excel(
    "./../../upgrade_mandi/raw-sheets-dump/blinkit/jpgtoexcel_table.xlsx",
    sheet_name="Sheet1",
)

In [20]:
item_id

     Item ID            UPC
0   10007246  5512398000011
1   10098526  5511321002500
2   10123183  5512045001000
3   10120912  5511909002000
4   10024615  5511327002000
5   10098524  5511319002500
6   10013376  5512432001000
7   10098530  5511325002000
8   10013425  5511882002000
9   10122454  5512007002500
10  10004112  5512375000011
11  10083107  5511174005000
12  10003979  5511561002000
13  10120914  5511911002000
14  10125442  5512158001000
15  10002273  5512013000011
16  10123176  5512053002500
17  10013485  5512597001000
18  10129883  5512167000011
19  10122453  5512006002500
20  10123157  5512026002000
21  10118121  5511827001750
22  10002287  3601476000011
23  10024292  3604625000011
24  10013985  5511768002500

In [ ]:
raw_file["Item ID"]  =raw_file["Item ID"].apply(lambda x: 0 if str(x).lower().strip() == "nan" else int(x))

In [ ]:
newDf = raw_file.merge(item_id, how="inner", left_on="Item ID", right_on="Item ID")

In [23]:
newDf

,Item ID,Item Name,HP Product ID,UOM,Final Indent (Qty) Dis,Vendor Name,UPC
0,10098526,Bitter Gourd - Cut(Pack),138829,250 g,32,Upgrade mandi cut,5511321002500
1,10123183,Brown Coconut Chunks(Punnet),143512,100 g,146,Upgrade mandi cut,5512045001000
2,10120912,Cauliflower Florets(Box),141996,200 g,110,Upgrade mandi cut,5511909002000
3,10098524,French Beans Cut(Pack),134040,250 g,56,Upgrade mandi cut,5511319002500
4,10013376,Ginger Chopped (Pack),147489,100 g,39,Upgrade mandi cut,5512432001000
5,10122454,Green Pumpkin - Cut(Packet),143031,250 g,51,Upgrade mandi cut,5512007002500
6,10004112,Green Pumpkin (Pack),146575,1 piece (400 g),99,Upgrade mandi cut,5512375000011
7,10125442,Peeled Garlic (Pack),144008,100 g,654,Upgrade mandi cut,5512158001000
8,10002273,Pineapple - Peeled(Pack),145146,1 piece (300 g),57,Upgrade mandi cut,5512013000011
9,10013485,Pomegranate Peeled (Pack),149534,100 g,69,Upgrade mandi cut,5512597001000
10,10129883,Portion Pumpkin (Bag),146451,1 pack (500 g),236,Upgrade mandi cut,5512167000011
11,10122453,Pulao Mix (Packet),143030,250 g,92,Upgrade mandi cut,5512006002500
12,10123157,Sambhar Veggie Mix - Cut(Punnet),143486,200 g,42,Upgrade mandi cut,5512026002000
13,10002287,Sweet Corn - Packet(Pack),133192,180 g - 200 g,192,Upgrade mandi cut,3601476000011
14,10013985,White Oyster Mushroom (Box),157237,125 g,55,Upgrade mandi cut,5511768002500

In [24]:
newDf["Date"] = date.today().strftime("%d-%m-%Y")
newDf["Best Before Date"] = (datetime.now() + timedelta(days=6)).strftime("%d-%m-%Y")

In [27]:
finalDf = newDf.loc[newDf.index.repeat(newDf["Final Indent (Qty) Dis"])][
    ["Item Name", "UOM", "Date", "Best Before Date", "UPC"]
].reset_index(drop=True)

In [29]:
finalDf.to_excel("blinkit sticker.xlsx", index=False)

In [28]:
finalDf

,Item Name,UOM,Date,Best Before Date,UPC
0,Bitter Gourd - Cut(Pack),250 g,21-08-2026,27-08-2026,5511321002500
1,Bitter Gourd - Cut(Pack),250 g,21-08-2026,27-08-2026,5511321002500
2,Bitter Gourd - Cut(Pack),250 g,21-08-2026,27-08-2026,5511321002500
3,Bitter Gourd - Cut(Pack),250 g,21-08-2026,27-08-2026,5511321002500
4,Bitter Gourd - Cut(Pack),250 g,21-08-2026,27-08-2026,5511321002500
...,...,...,...,...,...
1925,White Oyster Mushroom (Box),125 g,21-08-2026,27-08-2026,5511768002500
1926,White Oyster Mushroom (Box),125 g,21-08-2026,27-08-2026,5511768002500
1927,White Oyster Mushroom (Box),125 g,21-08-2026,27-08-2026,5511768002500
1928,White Oyster Mushroom (Box),125 g,21-08-2026,27-08-2026,5511768002500
1929,White Oyster Mushroom (Box),125 g,21-08-2026,27-08-2026,5511768002500