In [14]:
from utils.read import readExcel

import pandas as pd

In [15]:
df, dtype = readExcel(
    "./../../upgrade_mandi/raw-sheets-dump/vnd.openxmlformats-officedocument.spreadsheetml.sheet&rendition=1.xlsx",
    sheetName="Sheet1",
)

df.columns = [column.strip().lower() for column in df.columns]

df["indents"] = df["indents"].apply(int)

In [16]:
df

,date,city,store id,sku_id,store_name,vendor,item_code,product_name,weight,indents,supplier id,cost,mrp,po number,entity name
0,2026-06-01,Nagpur,1393571.0,OFFCYSLFFM,Mahal,Upgrade Mandi,804342.0,Alphonso Mango (Hapus),1Piece,1,74227878.0,64.0,80.00,20260601-1393571-74227878,RAJIDI RETAIL PVT LTD
1,2026-06-01,Nagpur,1397624.0,FJHV6XPAAT,Dharampeth,Upgrade Mandi,804342.0,Alphonso Mango (Hapus),1Piece,1,74227878.0,64.0,80.00,20260601-1397624-74227878,SWINSTA ENT PRIVATE LIMITED
2,2026-06-01,Nagpur,1392084.0,TPSQML9LX9,Byramji,Upgrade Mandi,17042.0,Alphonso Mango (Hapus),3Pieces,1,74227878.0,175.0,218.75,20260601-1392084-74227878,RAJIDI RETAIL PVT LTD
3,2026-06-01,Nagpur,1397035.0,DA7SD9YWW4,Nandavan,Upgrade Mandi,804342.0,Alphonso Mango (Hapus),1Piece,1,74227878.0,64.0,80.00,20260601-1397035-74227878,SWINSTA ENT PRIVATE LIMITED
4,2026-06-01,Nagpur,1392532.0,FDT60O4WQP,Manish Nagar,Upgrade Mandi,804342.0,Alphonso Mango (Hapus),1Piece,1,74227878.0,64.0,80.00,20260601-1392532-74227878,RAJIDI RETAIL PVT LTD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,2026-06-01,Nagpur,1397035.0,PF24KCFRTN,Nandavan,Upgrade Mandi,9497.0,Yellow Shevanti Flowers,100g,1,74227878.0,30.0,37.50,20260601-1397035-74227878,SWINSTA ENT PRIVATE LIMITED
424,2026-06-01,Nagpur,1393571.0,F04ZK4FSSP,Mahal,Upgrade Mandi,9497.0,Yellow Shevanti Flowers,100g,1,74227878.0,30.0,37.50,20260601-1393571-74227878,RAJIDI RETAIL PVT LTD
425,2026-06-01,Nagpur,1399707.0,APYXLPGR2Y,Sai Mandir,Upgrade Mandi,9497.0,Yellow Shevanti Flowers,100g,1,74227878.0,30.0,37.50,20260601-1399707-74227878,SWINSTA ENT PRIVATE LIMITED
426,2026-06-01,Nagpur,1392532.0,SXM30PLTJ5,Manish Nagar,Upgrade Mandi,9497.0,Yellow Shevanti Flowers,100g,1,74227878.0,30.0,37.50,20260601-1392532-74227878,RAJIDI RETAIL PVT LTD
427,2026-06-01,Nagpur,1397624.0,PRJGKMQSVF,Dharampeth,Upgrade Mandi,9497.0,Yellow Shevanti Flowers,100g,1,74227878.0,30.0,37.50,20260601-1397624-74227878,SWINSTA ENT PRIVATE LIMITED

In [17]:
df.columns

Index(['date', 'city', 'store id', 'sku_id', 'store_name', 'vendor',
       'item_code', 'product_name', 'weight', 'indents', 'supplier id', 'cost',
       'mrp', 'po number', 'entity name'],
      dtype='str')

In [ ]:
groupByProductName = df.groupby("item_code")

In [65]:
columnOrder = ["Product Name", "Item Code", "Weight", "Indents", "Final"]

final = groupByProductName.agg(
    {"product_name": "first", "weight": "first", "indents": "sum"}
).sort_values(by="product_name")

final["Final"] = (
    final["weight"]
    .apply(
        lambda weight: "".join(
            [char for char in weight if 48 <= ord(char) and ord(char) <= 57]
        )
    )
    .astype(int)
    * final["indents"]
)
final = final.reset_index()
final.index = final.index + 1

final["item_code"] = final["item_code"].astype(int)
final = final.rename(
    {
        "product_name": "Product Name",
        "weight": "Weight",
        "indents": "Indents",
        "item_code": "Item Code",
    },
    axis=1,
)

In [66]:
final

    Item Code                      Product Name   Weight  Indents  Final
1      804342            Alphonso Mango (Hapus)   1Piece        7      7
2       17042            Alphonso Mango (Hapus)  3Pieces        6     18
3        6755  Alphonso Mini Gems Mango (Hapus)  3Pieces        5     15
4       11565                Baby Banana (Keli)  4Pieces      107    428
5       38914                 Baby Bottle Gourd       1S      105    105
..        ...                               ...      ...      ...    ...
70       1296                    Tender Coconut   1Piece       88     88
71       7039                       White Onion     500g       24  12000
72       9498            White Shevanti Flowers     100g       15   1500
73      32331           Yellow Marigold Flowers     100g        7    700
74       9497           Yellow Shevanti Flowers     100g        5    500

[74 rows x 5 columns]

In [69]:
with pd.ExcelWriter("./../Final.xlsx", engine="xlsxwriter") as writer:
    final[columnOrder].to_excel(
        writer,
        sheet_name="Final Report",
        index=True,
        engine="openpyxl",
        freeze_panes=(1, 0),
        columns=columnOrder,
        index_label="Sr No",
    )

    workbook = writer.book
    worksheet = writer.sheets["Final Report"]

    # 4. Set custom column widths (Syntax: first_col, last_col, width)
    # worksheet.set_column("A:A", 25)  # Set column A width to 25
    worksheet.set_column("B:B", 40)  # Set column B width to 10
    # worksheet.set_column("C:C", 30)  # Set column C width to 30